### ISSUE TITLE
Windows 10, changing the device for sound output does not work

### ISSUE THREAD

**Issue by Glazami** [Frank-Friemel/Shairport4w#16]
Windows 10, changing the device for sound output does not work, after changing the device nothing happens, the sound is played only on the device set in the operating system by default.

**Comment by Swordfishx86** [comment]
https://github.com/Frank-Friemel/Shairport4w/issues/5#issuecomment-619560312

**Comment by Frank-Friemel** [comment]
Should be fixed with version 1.0.9.6 https://github.com/Frank-Friemel/Shairport4w/releases/tag/1.0.9.6
