### ISSUE TITLE
Multi-language

### ISSUE THREAD

**Issue by maboroshin** [Frank-Friemel/Shairport4w#25]
I added Japanese (language code 1041) using Resource Hacker and it is displayed.

It looks like it could be added to ```Shairport4w.rc```. If possible, please add the following text.
[Shairport4w.Japanese.rc.txt](https://github.com/Frank-Friemel/Shairport4w/files/10201823/Shairport4w.Japanese.rc.txt)

The following values were increased. It was too narrow for Japanese strings.
```
IDC_LOG_TO_FILE,11,106,61,10
IDC_NO_META_INFO,75,106,92,10
DC_NO_NEDIA_CONTROLS,75,117,121,10

IDC_TRAY,8,64,46,10
IDC_AUTOSTART,8,86,65,10

The following has been adjusted for alignment However, left alignment would be more versatile.
    LTEXT           "Airport name",IDC_STATIC,24, 10, 43, 8
    LTEXT           "Password",IDC_STATIC,25, 28, 43, 8
    LTEXT           "Verify password",IDC_STATIC,12,46,52,8

```

**Comment by Frank-Friemel** [comment]
Please download the new release (https://github.com/Frank-Friemel/Shairport4w/releases/tag/1.0.9.5) and check if they're included correctly. Thank you very much for your contribution

**Comment by maboroshin** [comment]
Thanks! Japanese translation is displayed perfectly! I was surprised at the quick update.

Please list my credit here : https://github.com/Frank-Friemel/Shairport4w/releases/tag/1.0.9.5
```Japanese translator: @maborosohin```
