### ISSUE TITLE
Characters in album/track/artist not displayed properly

### ISSUE THREAD

**Issue by olivierlevon** [Frank-Friemel/Shairport4w#27]
Example for artist  Miloš Karadaglić :
![SP4W Milos](https://user-images.githubusercontent.com/719804/208268119-9ab6b4f3-b8ac-4ea1-a92d-cbf6f56f7de5.png)
When replacing font MS Sans Serif by MS Shell Dlg everywhere in file https://github.com/Frank-Friemel/Shairport4w/blob/c7c9b901207daaf306e57527c78631fb978a41e2/src/Shairport4w.rc#L223, everything is OK : 
![SP4W Milos OK](https://user-images.githubusercontent.com/719804/208268122-d0aefbe7-5eb1-4c7f-b94d-c731439aff26.png)

**Comment by olivierlevon** [comment]
Proposed patch : 
--- C:/Users/parap/AppData/Local/Temp/TortoiseGit/Shairport4w-c7c9b901.002.rc	Sat Dec 17 23:23:27 2022
+++ C:/Users/parap/Desktop/SP4W/Shairport4w_FF-git/src/Shairport4w.rc	Sat Dec 17 22:02:36 2022
@@ -220,7 +220,7 @@
 IDD_ABOUTBOX DIALOGEX 0, 0, 255, 180
 STYLE DS_SETFONT | DS_MODALFRAME | WS_POPUP | WS_CAPTION | WS_SYSMENU
 CAPTION "About"
-FONT 8, "MS Sans Serif", 0, 0, 0x0
+FONT 8, "MS Shell Dlg", 0, 0, 0x0
 BEGIN
     GROUPBOX        "",IDC_STATIC_FRAME,7,7,241,166
     ICON            IDR_MAINFRAME,IDC_STATIC,116,26,20,20
@@ -235,7 +235,7 @@
 STYLE DS_SETFONT | DS_MODALFRAME | WS_MINIMIZEBOX | WS_CLIPSIBLINGS | WS_CAPTION | WS_SYSMENU
 CAPTION "Shairport4w"
 MENU IDR_MAINMENU
-FONT 8, "MS Sans Serif", 0, 0, 0x0
+FONT 8, "MS Shell Dlg", 0, 0, 0x0
 BEGIN
     GROUPBOX        "",IDC_STATUS_PANEL,7,3,194,19
     LTEXT           "",IDC_STATIC_STATUS,13,10,182,8,SS_ENDELLIPSIS
@@ -547,7 +547,7 @@
 IDD_ABOUTBOX DIALOGEX 0, 0, 255, 182
 STYLE DS_SETFONT | DS_MODALFRAME | WS_POPUP | WS_CAPTION | WS_SYSMENU
 CAPTION "Über"
-FONT 8, "MS Sans Serif", 0, 0, 0x0
+FONT 8, "MS Shell Dlg", 0, 0, 0x0
 BEGIN
     GROUPBOX        "",IDC_STATIC_FRAME,7,7,241,168
     ICON            IDR_MAINFRAME,IDC_STATIC,116,26,20,20
@@ -599,7 +599,7 @@
 STYLE DS_SETFONT | DS_MODALFRAME | WS_MINIMIZEBOX | WS_CLIPSIBLINGS | WS_CAPTION | WS_SYSMENU
 CAPTION "Shairport4w"
 MENU IDR_MAINMENU
-FONT 8, "MS Sans Serif", 0, 0, 0x0
+FONT 8, "MS Shell Dlg", 0, 0, 0x0
 BEGIN
     GROUPBOX        "",IDC_STATUS_PANEL,7,3,194,19
     LTEXT           "",IDC_STATIC_STATUS,13,10,182,8,SS_ENDELLIPSIS
@@ -919,7 +919,7 @@
 IDD_ABOUTBOX DIALOGEX 0, 0, 255, 180
 STYLE DS_SETFONT | DS_MODALFRAME | WS_POPUP | WS_CAPTION | WS_SYSMENU
 CAPTION "このソフトについて"
-FONT 8, "MS Sans Serif", 0, 0, 0x0
+FONT 8, "MS Shell Dlg", 0, 0, 0x0
 BEGIN
     GROUPBOX        "",IDC_STATIC_FRAME,7,7,241,166
     ICON            IDR_MAINFRAME,IDC_STATIC,116,26,20,20
@@ -934,7 +934,7 @@
 STYLE DS_SETFONT | DS_MODALFRAME | WS_MINIMIZEBOX | WS_CLIPSIBLINGS | WS_CAPTION | WS_SYSMENU
 CAPTION "Shairport4w"
 MENU IDR_MAINMENU
-FONT 8, "MS Sans Serif", 0, 0, 0x0
+FONT 8, "MS Shell Dlg", 0, 0, 0x0
 BEGIN
     GROUPBOX        "",IDC_STATUS_PANEL,7,3,194,19
     LTEXT           "",IDC_STATIC_STATUS,13,10,182,8,SS_ENDELLIPSIS

**Comment by Frank-Friemel** [comment]
Should be fixed with version 1.0.9.6 https://github.com/Frank-Friemel/Shairport4w/releases/tag/1.0.9.6
