### ISSUE TITLE
Strange issue where newer version of Shairport4w does not work but older version does

### ISSUE THREAD

**Issue by Rocketboy235** [Frank-Friemel/Shairport4w#38]
So I finally try upgrading the old version of Shairport4w on my laptop... Trying to use v1.0.9.7 on my laptop as the airplay receiver but my iPhone and my iTunes on my other computer are unable to see the receiver.

I checked firewall and made sure its unblocked as well as restart bonjour service. Unfortunately no luck. I switch back to my older version of Shairport4w (v1.0.8.8 and that works).

Scratching my head as to what I might be missing here.

**Comment by super-lurker** [comment]
can you send me that old version? the oldest ver this repo have is 1.9.4
I'd really appreciate it. thanks :)
