### ISSUE TITLE
Airplay 2

### ISSUE THREAD

**Issue by pillepalle123** [Frank-Friemel/Shairport4w#4]
This is pretty great and works right away! Many thanks!

Are there any plans for Airplay 2 support? (if that's anyway doable at all)

**Comment by Frank-Friemel** [comment]
Sorry, but this is not possible. As far as I know there is no documentation about Airplay 2 neither anybody has done some reverse engineering (as James Laird did with Airplay 1)

**Comment by breyed** [comment]
There's been work on Airplay 2 at mikebrady/shairport-sync#535. Hopefully once complete, a port will be practical.

**Comment by a-gadish** [comment]
https://github.com/mikebrady/shairport-sync/ has really come a long way, any chance you're interested in porting over for shairport4w??
